backend/config/routes.rb
Rails.application.routes.draw do
  resources :acompanhas, :segues, :usuarios, :posts, :caracteristicas

  root 'sessions#new'
 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'cadastro', to: 'segues#new'

  get 'resultado', to: 'posts#busca'
  get 'busca', to: 'posts#index'

  post 'usuarios/:id/follow', to: 'usuarios#follow', as: "follow_usuario"
  post 'usuarios/:id/unfollow', to: 'usuarios#unfollow', as: "unfollow_usuario"
  
  get 'feed', to: 'usuarios#feed'

  resources :posts


end

backend/app/models/post.rb
class Post < ApplicationRecord

    validates :titulo, presence: true

    has_one_attached :foto

    belongs_to :usuario

    acts_as_taggable_on :tags

end

backend/app/controllers/posts_controller.rb
class PostsController < ApplicationController


    def show
        @post = Post.find(params[:id])
        @posts_relacionados = @post.find_related_tags
    end

    def index
        @posts = Post.all
        @busca = Post.tagged_with(params[:search])
    end

    def busca
        @posts = Post.all
        @busca = Post.tagged_with(params[:search])
    end

    def new
        if usuario_atual.TipoDeConta == "Tatuador"
            @post = Post.new
        
        else
            redirect_to feed_path
        end
    end

    def edit
        @post = Post.find(params[:id])
        if @post.usuario_id != usuario_atual.id
            redirect_to feed_path
        end
    end
    
    def create
        if usuario_atual.TipoDeConta == "Tatuador"
            @post = Post.new(tag_params)
            @post.usuario = usuario_atual    

            if @post.save
                flash.notice = "Post salvo!"
                redirect_to post_path(@post)
            else
                render 'new'
            end
        
        else
            redirect_to feed_path    
        end
        end

        def update
            @post = Post.find(params[:id])
            if @post.update(params.require(:post).permit(:titulo, :foto, :usuario_id, :tag_list))
                flash.notice = "Post atualizado!"
                redirect_to post_path(@post)
                
            else 
                render 'edit' 
            end
    end

    def destroy
        @post = Post.find(params[:id])
        if @post.usuario_id == usuario_atual.id
            @post.destroy
            redirect_to posts_path
        else
            redirect_to feed_path
        end
    end
    def tagged
        if params[:tag].present?
            @posts = Post.tagged_with(params[:tag])
        else
            @posts = Post.all
        end
    end

    def tag_params
        p = params.require(:post).permit(:titulo, :foto, :estilo, :tag_list)

        p[:tag_list].split(',') do |tag|
            Caracteristica.create(:Descricao=> tag, :Estilo=>false)
        end

        p[:estilo].split(',') do |tag|
            Caracteristica.create(:Descricao=> tag, :Estilo=>true)
        end

        p[:tag_list] = p[:tag_list] + ',' + p[:estilo]

        p.permit(:titulo, :foto, :tag_list)
    end


end

backend/app/views/posts/busca.html.erb
<h1> Resultado da busca pela tag "<%= params[:search] %>" </h1>


<% @busca.each do |post| %>
<ul>
    <li><%= link_to post.titulo, post_path(post) %></li>
</ul>
<% end %>

<%= link_to 'Voltar', posts_path %>

backend/app/views/posts/edit.html.erb
   <% if logado? && usuario_atual.TipoDeConta == 'Tatuador' && @post.usuario == usuario_atual %>
   
   <h1> Editar post: </h1>

   <% if @post.errors.any? %>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
         <li> <%= msg %> 
      <% end %>
      </ul>
   <% end %>



   <%= form_with(model: @post, local: true) do |form| %>

   <p>
   <%= form.label "Titulo: " %>
   <%= form.text_field :titulo %>
   </p>


   <div class="field">
      <%= form.label "Foto: " %>
      <%= form.file_field :foto %>
   </div>

   <div class="field">
      <%= form.label "Tags: " %>
      <%= form.text_field :tag_list %>
   </div>

   <%= form.submit "Salvar post" %>

   <% end %>

<% else %>
<h1> Seu tipo de conta não dá permissão para acessar essa página. </h1>

<%= link_to 'Voltar', posts_path %>
<%end%>

backend/app/views/posts/index.html.erb
<h1> Index: </h1>

<h4> busca por tags: </h4>
    <%= form_tag(resultado_path, method: :get) do %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag("Search") %>
    <% end %>

<br><br>

<table>
    <thead>
        <tr>
            <th>Titulo: </th>
            <th>Criador: </th>
            <th>Ações: </th>
        </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
        <tr>
            <td> <%=post.titulo %> </td>
            <td> <%= post.usuario.NomeDeUsuario %> </td>
            <td> <%= link_to 'Ver', post_path(post.id) %></td>
            <% if logado? && post.usuario == usuario_atual %>
            <td> <%= link_to 'Delete', post_path(post.id), method: :delete, data: {confirm: "Você tem certeza?"} %></td>
            <td> <%= link_to 'Editar', edit_post_path(post.id)%></td>
            <% end %>
        </tr>
    <% end %>    
    </tbody>

</table>

<br>


<% if logado? && usuario_atual.TipoDeConta == 'Tatuador' %>
<%= link_to 'Novo Post', new_post_path %>
<% end %>

backend/app/views/posts/new.html.erb
<% if logado? && usuario_atual.TipoDeConta == 'Tatuador' %>

   <h1> Criar um post novo: </h1>

   <% if @post.errors.any? %>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
         <li> <%= msg %> 
      <% end %>
      </ul>
   <% end %>



   <%= form_with scope: :post, url: posts_path, local: true do |form| %>

   <p>
   <%= form.label "Titulo: " %>
   <%= form.text_field :titulo %>
   </p>

   <div class="field">
      <%= form.label "Foto: " %>
      <%= form.file_field :foto %>
   </div>

   <div class="field">
      <%= form.label "Estilo: "%>
      <%= form.text_field :estilo%>
   </div>

   <div class="field">
      <%= form.label "Tags: " %>
      <%= form.text_field :tag_list %>
   </div>

   <%= form.submit "Salvar post" %>

   <% end %>

<% else %>
<h1> Seu tipo de conta não dá permissão para acessar essa página. </h1>

<%= link_to 'Voltar', posts_path %>
<%end%>

backend/app/views/posts/show.html.erb
<h1>Posts</h1>

<p><b>Titulo:  </b><%=@post.titulo %></p>

<p>
  <% if @post.foto.attached? %>
  <img src ="<%=(url_for(@post.foto))%>">

  <% else %>
  <%= "nao possui foto." %>

  <% end %>
</p>

<p><b>Autor:  </b><%= @post.usuario.NomeDeUsuario %></p>

<p>
  <b>Tags:</b>
  <ul>
  <% @post.tag_list.each do |tag| %>
    <li><%= tag %></li>
  <% end %>
  </ul>
</p>

<p>
  <h4> Posts relacionados: </h4>
    <ul>
      <% @posts_relacionados.each do |relacionado| %>
        <li><%= link_to relacionado.titulo, relacionado %></li>
      <% end %>
    </ul>
  </h4>
</p>



<br><br>
<% if logado? && @post.usuario == usuario_atual %>
<%= link_to 'Editar', edit_post_path(@post) %>
<%= link_to 'Deletar', post_path(@post), method: :delete, data: {confirm: "Você tem certeza?"} %>
<% end %>
<%= link_to 'Voltar', feed_path %>