backend/config/routes.rb
Rails.application.routes.draw do
  resources :acompanhas, :segues, :usuarios, :posts, :caracteristicas

  root 'sessions#new'
 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'cadastro', to: 'segues#new'

  get 'resultado', to: 'posts#busca'
  get 'busca', to: 'posts#index'

  post 'usuarios/:id/follow', to: 'usuarios#follow', as: "follow_usuario"
  post 'usuarios/:id/unfollow', to: 'usuarios#unfollow', as: "unfollow_usuario"
  
  get 'feed', to: 'usuarios#feed'

  resources :posts


end

backend/app/models/caracteristica.rb
class Caracteristica < ApplicationRecord
    has_many :usuarios, through: :segues
    has_many :tatuadors, through: :especializado_ems
    has_many :tatuagems, through: :possuis
    has_many :possuis
    has_many :segues
    has_many :especializado_ems

    validates :Descricao ,presence: true, uniqueness: true
end

backend/app/controllers/caracteristicas_controller.rb
class CaracteristicasController < ApplicationController
  before_action :set_caracteristica, only: [:show, :edit, :update, :destroy]

  # GET /caracteristicas
  # GET /caracteristicas.json
  def index
    @caracteristicas = Caracteristica.all
    redirect_to root_path
  end

  # GET /caracteristicas/1
  # GET /caracteristicas/1.json
  def show
    redirect_to root_path
  end

  # GET /caracteristicas/new
  def new
    @caracteristica = Caracteristica.new
    redirect_to root_path
  end

  # GET /caracteristicas/1/edit
  def edit
    redirect_to root_path
  end

  # POST /caracteristicas
  # POST /caracteristicas.json
  def create
    @caracteristica = Caracteristica.new(caracteristica_params)

    respond_to do |format|
      if @caracteristica.save
        format.html { redirect_to @caracteristica, notice: 'Caracteristica was successfully created.' }
        format.json { render :show, status: :created, location: @caracteristica }
      else
        format.html { render :new }
        format.json { render json: @caracteristica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caracteristicas/1
  # PATCH/PUT /caracteristicas/1.json
  def update
    respond_to do |format|
      if @caracteristica.update(caracteristica_params)
        format.html { redirect_to @caracteristica, notice: 'Caracteristica was successfully updated.' }
        format.json { render :show, status: :ok, location: @caracteristica }
      else
        format.html { render :edit }
        format.json { render json: @caracteristica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caracteristicas/1
  # DELETE /caracteristicas/1.json
  def destroy
    redirect_to root_path
    @caracteristica.destroy
    respond_to do |format|
      format.html { redirect_to caracteristicas_url, notice: 'Caracteristica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caracteristica
      @caracteristica = Caracteristica.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caracteristica_params
      params.require(:caracteristica).permit(:Descricao, :Estilo)
    end
end

backend/app/helpers/caracteristicas_helper.rb
module CaracteristicasHelper
end

backend/app/views/caracteristicas/_form.html.erb
<%= form_with(model: caracteristica, local: true) do |form| %>
  <% if caracteristica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caracteristica.errors.count, "error") %> prohibited this caracteristica from being saved:</h2>

      <ul>
        <% caracteristica.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Descricao %>
    <%= form.text_field :Descricao %>
  </div>

  <div class="field">
    <%= form.label :Estilo %>
    <%= form.check_box :Estilo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/caracteristicas/edit.html.erb
<h1>Editing Caracteristica</h1>

<%= render 'form', caracteristica: @caracteristica %>

<%= link_to 'Show', @caracteristica %> |
<%= link_to 'Back', caracteristicas_path %>

backend/app/views/caracteristicas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Caracteristicas</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Estilo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caracteristicas.each do |caracteristica| %>
      <tr>
        <td><%= caracteristica.Descricao %></td>
        <td><%= caracteristica.Estilo %></td>
        <td><%= link_to 'Show', caracteristica %></td>
        <td><%= link_to 'Edit', edit_caracteristica_path(caracteristica) %></td>
        <td><%= link_to 'Destroy', caracteristica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caracteristica', new_caracteristica_path %>

backend/app/views/caracteristicas/new.html.erb
<h1>New Caracteristica</h1>

<%= render 'form', caracteristica: @caracteristica %>

<%= link_to 'Back', caracteristicas_path %>

backend/app/views/caracteristicas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @caracteristica.Descricao %>
</p>

<p>
  <strong>Estilo:</strong>
  <%= @caracteristica.Estilo %>
</p>

<%= link_to 'Edit', edit_caracteristica_path(@caracteristica) %> |
<%= link_to 'Back', caracteristicas_path %>