backend/config/routes.rb
Rails.application.routes.draw do
  resources :acompanhas, :segues, :usuarios, :posts, :caracteristicas

  root 'sessions#new'
 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'cadastro', to: 'segues#new'

  get 'resultado', to: 'posts#busca'
  get 'busca', to: 'posts#index'

  post 'usuarios/:id/follow', to: 'usuarios#follow', as: "follow_usuario"
  post 'usuarios/:id/unfollow', to: 'usuarios#unfollow', as: "unfollow_usuario"
  
  get 'feed', to: 'usuarios#feed'

  resources :posts


end

backend/app/models/segue.rb
class Segue < ApplicationRecord
  belongs_to :usuario
  belongs_to :caracteristica

  validates_uniqueness_of :caracteristica, scope: [:usuario]
end

backend/app/controllers/segues_controller.rb
class SeguesController < ApplicationController
  before_action :set_segue, only: [:show, :edit, :update, :destroy]

  # GET /segues
  # GET /segues.json
  def index
    @segues = Segue.all
    redirect_to root_path
  end
  
  # GET /segues/1
  # GET /segues/1.json
  def show
    redirect_to root_path
  end

  # GET /segues/new
  def new
    @segue = Segue.new
    @usuario = usuario_atual
    @caracteristicas = Caracteristica.all
  end

  # GET /segues/1/edit
  def edit
    @caracteristicas = Caracteristica.all
  end

  # POST /segues
  # POST /segues.json
  def create
    @caracteristicas = Caracteristica.all
    @not_error = 1
    @usuario_atual = usuario_atual()
    segue_params.each do |tag|
      @segue = Segue.new({:usuario_id => @usuario_atual.id, :caracteristica_id => tag})
      if @segue.save
      else
        @not_error = 0
      end
    end
    respond_to do |format|
      if @not_error
        format.html { redirect_to feed_url, notice: 'Suas tags foram adicionadas!' }
        format.json { render :show, status: :created, location: @segue }
      else
        format.html { render :new }
        format.json { render json: @segue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segues/1
  # PATCH/PUT /segues/1.json
  def update
    @caracteristicas = Caracteristica.all
    @not_error = 1
    @usuario_atual = usuario_atual()
    segue_params.each do |tag|
      if @segue.update({:usuario_id => @usuario_atual.id, :caracteristica_id => tag})
      else
        @not_error = 0
      end
    end
    respond_to do |format|
      if @not_error
        format.html { redirect_to feed_url, notice: 'Suas tags foram adicionadas!' }
        format.json { render :show, status: :created, location: @segue }
      else
        format.html { render :new }
        format.json { render json: @segue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segues/1
  # DELETE /segues/1.json
  def destroy
    @segue.destroy
    respond_to do |format|
      format.html { redirect_to segues_url, notice: 'Segue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segue
      @segue = Segue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def segue_params
      tags = params.require(:tags)
    end
end

backend/app/helpers/segues_helper.rb
module SeguesHelper
end

backend/app/views/segues/_form.html.erb
<%= form_with(model: @segue, local:true) do |form| %>
  <% if @segue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segue.errors.count, "error")%> prohibited this segue from being saved:</h2>
      
      <ul>
        <% @segue.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <ul>
    <% @caracteristicas.each do |tag| %>
        <li>
          <%= check_box_tag 'tags[]', tag.id -%>
          <%= h tag.Descricao -%>
        </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit 'Save' %>
  </div>
  
<% end %>

backend/app/views/segues/edit.html.haml
%h1 Editing segue

= render 'form'

= link_to 'Show', @segue
\|
= link_to 'Back', segues_path

backend/app/views/segues/index.html.haml
%h1 Listing segues

%table
  %thead
    %tr
      %th Usuario
      %th Caracteristica
      %th
      %th
      %th

  %tbody
    - @segues.each do |segue|
      %tr
        %td= segue.usuario.Nome
        %td= segue.caracteristica.Descricao
        %td= link_to 'Show', segue
        %td= link_to 'Edit', edit_segue_path(segue)
        %td= link_to 'Destroy', segue, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Segue', new_segue_path

backend/app/views/segues/new.html.erb
<p id="notice"><%= notice %></p>

<h1> SEUS GOSTOS </h1>

<h3> Escolha até 5 tags para seguir </h3>

<%= render 'form' %>

<%= link_to 'Back', segues_path%>

backend/app/views/segues/show.html.haml
%p#notice= notice

%p
  %b Usuario:
  = @segue.usuario.Nome
%p
  %b Caracteristica:
  = @segue.caracteristica.Descricao

= link_to 'Edit', edit_segue_path(@segue)
\|
= link_to 'Back', segues_path