backend/config/routes.rb
Rails.application.routes.draw do
  resources :acompanhas, :segues, :usuarios, :posts, :caracteristicas

  root 'sessions#new'
 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'cadastro', to: 'segues#new'

  get 'resultado', to: 'posts#busca'
  get 'busca', to: 'posts#index'

  post 'usuarios/:id/follow', to: 'usuarios#follow', as: "follow_usuario"
  post 'usuarios/:id/unfollow', to: 'usuarios#unfollow', as: "unfollow_usuario"
  
  get 'feed', to: 'usuarios#feed'

  resources :posts


end

backend/app/models/usuario.rb
class Usuario < ApplicationRecord
    has_many :tatuadors, through: :acompanhas
    has_many :tatuagens, through: :salvas
    has_many :caracteristicas, through: :segues
    has_many :acompanhas
    has_many :salvas
    has_many :segues
    has_many :posts, through: :segues

    # um usuario pode acompanhar varios usuarios
    has_many :usuarios_acompanhados, foreign_key: :acompanha_id, class_name: "Acompanha"
    has_many :acompanhados, through: :usuarios_acompanhados

    # um usuario pode ser acompanhado por varios usuarios
    has_many :usuarios_que_acompanham, foreign_key: :acompanhado_id, class_name: "Acompanha"
    has_many :acompanhas, through: :usuarios_que_acompanham


    REGEX_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i


    validates :Nome ,presence: true
    validates :Email ,presence: true, uniqueness: {case_sensitive: false}, format: {with: REGEX_EMAIL }
    validates :CPF ,presence: true, uniqueness: true
    validates :NomeDeUsuario ,presence: true, uniqueness: true
 

    has_secure_password
    has_one_attached :foto_de_perfil

    
end

backend/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :requer_usuario, except: [:show, :new, :create]
  before_action :requer_mesmo_usuario, only: [:edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @posts = Post.all
  end

  # GET /usuarios/new
  def new
    if !logado?
      @usuario = Usuario.new
    else
      redirect_to feed_path
    end
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    respond_to do |format|
      if @usuario.save
        session[:usuario_id] = @usuario.id
        format.html { redirect_to cadastro_url, notice: 'Seu perfil foi criado!' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Seu perfil foi atualizado.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    if usuario_atual != @usuario
      @usuario.destroy
      session[:usuario_id] = nil
      redirect_to root_path
      flash.alert = "Usuario deletado com sucesso."
    
    else
      redirect_to feed_path  
    end
  end

  def follow
    @usuario = Usuario.find(params[:id])
    usuario_atual.acompanhados << @usuario
    redirect_to usuario_path(@usuario)
  end

  def unfollow
    @usuario = Usuario.find(params[:id])
    usuario_atual.usuarios_acompanhados.find_by(acompanhado_id: @usuario.id).destroy
    redirect_to usuario_path(@usuario)
  end


  def feed
    @acompanhados = usuario_atual.usuarios_acompanhados
    @posts = Post.all
    @tags_seguidas = usuario_atual.segues
    @segues = Segue.all
    @caracteristicas = Caracteristica.all

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:Nome, :Email, :CPF, :NomeDeUsuario, :password, :TipoDeConta, :Foto, :Sobre, :Celular, :Instagram, :NumeroDeSeguidores, :foto_de_perfil )
    end

    def requer_mesmo_usuario
      if usuario_atual != @usuario
        flash.alert = "Você só pode deletar ou editar o próprio perfil!"
        redirect_to usuarios_path
      end
    end


end

backend/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

backend/app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= form.label "Foto de Perfil: " %>
   <%= form.file_field :foto_de_perfil %>
  </div>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :Nome %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.email_field :Email %>
  </div>

  <div class="field">
    <%= form.label "Nome de Usuario" %>
    <%= form.text_field :NomeDeUsuario %>
  </div>

   <div class="field">
    <%= form.label "Password:" %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :CPF %>
    <%= form.text_field :CPF %>
  </div>
 
  <div class="field">
  <%= form.label "Tipo De Conta:" %>
  <%= form.select(:TipoDeConta, raw('<option value="Comum">Conta Comum</option>
                                     <option value="Tatuador">Tatuador</option>
                                    <option value="Estudio">Estudio</option>')) %>

  


  <% if @usuario.TipoDeConta == "Tatuador" %>
    <div class="field">
      <%= form.label :Celular %>
      <%= form.text_field :Celular %>
    </div>
    
    <div class="field">
      <%= form.label :Instagram %>
      <%= form.text_field :Instagram %>
    </div>
    
  <% end %>

  <div class="actions">
    <%= form.submit %>
  
  
  
  </div>
<% end %>

backend/app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

backend/app/views/usuarios/feed.html.erb
<p id="notice"><%= notice %></p>

<h1> Feed de <%= usuario_atual.Nome %></h1>
<br>

<% feed_content = [] %>

<% @acompanhados.each do |usuario| %>
    <% @posts.each do |post| %>
        <% if usuario.acompanhado_id == post.usuario_id %>
            <% feed_content.push post %>
        <% end %>
    <% end %>    
<% end %>

<% @tags_seguidas.each do |tag| %>
    <% @caracteristicas.each do |car| %>
        <% if tag.caracteristica_id == car.id %>
            <% @posts.each do |post| %>
                <% if post.tag_list.include? car.Descricao %>
                    <% if !feed_content.include? post %>
                        <% feed_content.push post %>
                    <% end %>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

<% feed_content.each do |post| %>
    <% (feed_content.length).times do |j| %>
        <% while j > 0 %>
            <% if feed_content[j-1].created_at > feed_content[j].created_at %>
                <% feed_content[j], feed_content[j-1] = feed_content[j-1], feed_content[j] %>
            <% else %>
                <% break %>
            <% end %>
            <% j -= 1 %>
        <% end %>
    <% end %>
<% end %>


<% feed_content. each do |post| %>
<%= link_to post.titulo, post_path(post) %>, por <%= link_to Usuario.find_by(id: post.usuario_id).NomeDeUsuario, usuario_path(Usuario.find_by(id: post.usuario_id)) %> <br>
<% end %>

<br><br>
<%= link_to 'Logout', logout_path%>
<%= link_to "Voltar", posts_path %>

backend/app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Cpf</th>
      <th>Nome de Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.Nome %></td>
        <td><%= usuario.Email %></td>
        <td><%= usuario.CPF %></td>
        <td><%= usuario.NomeDeUsuario %></td>
        <td><%= link_to 'Show', usuario %></td>
        <% if logado? && usuario.NomeDeUsuario == @usuario_atual.NomeDeUsuario %>
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Excluir meu perfil', usuario_path(usuario_atual), method: :delete, data: {confirm: "Você é corno?"} %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if !logado? %>
<%= link_to 'New Usuario', new_usuario_path %>
<%end%>

backend/app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

backend/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @usuario.foto_de_perfil.attached? %>
  <img src ="<%=(url_for(@usuario.foto_de_perfil))%>">
  <% end %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.Nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.Email %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @usuario.CPF %>
</p>

<p>
  <strong>Nome de Usuario:</strong>
  <%= @usuario.NomeDeUsuario %>
</p>

<p>
  <strong>Tipo de Conta: </strong>
  <%= @usuario.TipoDeConta %>
</p>

<% if @usuario.TipoDeConta == 'Tatuador' %>
<p>
  <strong>Instagram: </strong>
  <%= @usuario.Instagram %>
</p>


<% end %>

<% if logado? && @usuario.NomeDeUsuario != usuario_atual.NomeDeUsuario %>
  <% if usuario_atual.acompanhados.include?(@usuario)%>
    <%= button_to "Unfollow", unfollow_usuario_path, method: "POST" %>
  <% else %>
    <%= button_to "Follow", follow_usuario_path, method: "POST"  %>
  <% end %>
<% end %>

<br><br>
<% if @usuario.TipoDeConta == "Tatuador" %>
<%= "Posts do usuario: " %>
  <% @posts.each do |post| %>
    <%if post.usuario.NomeDeUsuario == @usuario.NomeDeUsuario %>
    <ul>
      <li><%= link_to post.titulo, post_path(post) %></li>
    </ul>
    <% end %>
  <% end %>
<% end %>



<br>

<% if logado? && @usuario.NomeDeUsuario == usuario_atual.NomeDeUsuario %>
<%= link_to 'Edit', edit_usuario_path(usuario_atual) %>
<% end %>

<% if logado? && @usuario.NomeDeUsuario == usuario_atual.NomeDeUsuario && @usuario.TipoDeConta == "Tatuador" %>
  <%= link_to 'Novo Post', new_post_path %>
<% end %>

<% if logado? %>
<%= link_to 'Logout', logout_path, method: :delete %>
<% end %>

<%= link_to 'Back', usuarios_path %>